//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class GameSceneController : RSSceneController
{
	[SerializeField] private GameObject mapCentre;

	override public void OnLoad()
	{
		Debug.Log("Game scene finally loaded");
	}

	private void LoadLevel(int levelNum)
	{
		// Right now we actually only have one level

		// Clear the map

		// Load in new map data.
		TextAsset mazeTextAsset = Resources.Load("testMaze.txt") as TextAsset;
		if (mazeTextAsset == null) { return; }

		string text = mazeTextAsset.text;
	}
}


